version: '3'
services:
  site:
    command: >
      bash -c "export GOOGLE_CALENDAR_APIKEY=AIzaSyB9s6mgNy13Dx2WlbPoB9jNUnq1QdGqWEY && bundle install --path vendor/bundle && bundle exec jekyll serve --watch --livereload --host 0.0.0.0"
    build: .
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
